version: '3.4'

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  identifier:
    ports:
      - "80:80"
    restart: "no"
  dispatcher:
    restart: "no"
  database:
    ports:
      - "8890:8890"
    restart: "no"
  resource:
    restart: "no"
  export-meetings:
    ports:
      - "1212:80"
    restart: "no"
  publieksontsluiting-export:
    environment:
      NODE_ENV: "development"
      KALEIDOS_SPARQL_ENDPOINT: "http://kaleidos-db:8895/sparql"
    ports:
      - "8888:80"
    links:
      - database:database
    extra_hosts:
      - "kaleidos:172.17.0.1"
    restart: "no"
