version: '3.4'

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  identifier:
    image: semtech/mu-identifier:1.7.0
    links:
      - dispatcher:dispatcher
    labels:
      - "logging=true"
    restart: 'no'
    logging: *default-logging
  dispatcher:
    image: semtech/mu-dispatcher:1.1.2
    volumes:
      - ./config/dispatcher:/config
    labels:
      - "logging=true"
    restart: 'no'
    logging: *default-logging
  virtuoso:
    image: tenforce/virtuoso:1.3.2-virtuoso7.2.2
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    volumes:
      - ./data/db:/data
    labels:
      - "logging=true"
    restart: 'no'
    logging: *default-logging
  export:
    image: kanselarij/valvas-export-service
    environment:
      MU_SPARQL_ENDPOINT: "http://virtuoso:8890/sparql" # database for intermediate results
      KALEIDOS_SPARQL_ENDPOINT: "http://triplestore:8890/sparql" # database to export data from
    volumes:
      - ./data/exports/valvas:/data/exports
    labels:
      - "logging=true"
    restart: 'no'
    logging: *default-logging
  file-packaging:
    image: cecemel/simple-file-package-service:0.4.0
    environment:
      TARGET_FOLDER: "/data/files"
      DATA_FOLDER: "/data/original-files/"
      HOURS_DELIVERING_TIMEOUT: '3'
      PACKAGE_CRON_PATTERN: '0 0 0 0 1 *'
    links:
      - virtuoso:database
    volumes:
      - ./config/export/file-query.js:/app/file-query.js
      - ./data/files:/data/files
      # - /data/app-kaleidos/data/files:/data/original-files  # update to the Kaleidos file volume
