version: '3.4'

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  admin-frontend:
    image: kanselarij/frontend-valvas-admin:themis
    links:
      - identifier:backend
  identifier:
    image: semtech/mu-identifier:1.9.1
    links:
      - dispatcher:dispatcher
    labels:
      - "logging=true"
    restart: 'no'
    logging: *default-logging
  dispatcher:
    image: semtech/mu-dispatcher:1.1.2
    volumes:
      - ./config/dispatcher:/config
    labels:
      - "logging=true"
    restart: 'no'
    logging: *default-logging
  database:
    image: semtech/mu-authorization:0.6.0-beta.7
    environment:
      MU_SPARQL_ENDPOINT: "http://virtuoso:8890/sparql"
    volumes:
      - ./config/authorization:/config
    labels:
      - "logging=true"
    restart: 'no'
    logging: *default-logging
  delta-notifier:
    image: semtech/mu-delta-notifier:0.1.0
    volumes:
      - ./config/delta:/config
    restart: 'no'
    environment:
      DEBUG_DELTA_MATCH: "true"
      LOG_REQUESTS: "true"
    labels:
      - "logging=true"
    logging: *default-logging
  virtuoso:
    image: tenforce/virtuoso:1.3.2-virtuoso7.2.2
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    volumes:
      - ./data/db:/data
    labels:
      - "logging=true"
    restart: 'no'
    logging: *default-logging
  file:
    image: semtech/mu-file-service:3.1.2
    volumes:
      - ./data/exports:/share
    labels:
      - "logging=true"
    restart: 'no'
    logging: *default-logging
  kaleidos-public-file:
    image: kanselarij/public-file-service:4.0.0
    environment:
      MU_SPARQL_ENDPOINT: "http://triplestore:8890/sparql" # Kaleidos DB
      MU_APPLICATION_GRAPH: "http://mu.semte.ch/graphs/organizations/kanselarij"
    volumes:
      - ./data/files:/share # mount Kaleidos file folder
    labels:
      - "logging=true"
    restart: 'no'
    logging: *default-logging
  export:
    image: kanselarij/themis-export-service:1.3.1
    environment:
      MU_SPARQL_ENDPOINT: "http://database:8890/sparql" # database for results for which delta's must be generated
      VIRTUOSO_SPARQL_ENDPOINT: "http://virtuoso:8890/sparql" # database for intermediate results
      KALEIDOS_SPARQL_ENDPOINT: "http://triplestore:8890/sparql" # database to export data from
    volumes:
      - ./data/exports:/share
    labels:
      - "logging=true"
    restart: 'no'
    logging: *default-logging
  ttl-to-delta:
    image: redpencil/ttl-to-delta:1.0.0
    links:
      - database:database
    volumes:
      - ./data/exports:/share
    labels:
      - "logging=true"
    restart: 'no'
    logging: *default-logging
  publication-producer:
    image: kanselarij/themis-publication-producer:1.1.0
    links:
      - database:database
    labels:
      - "logging=true"
    restart: 'no'
    logging: *default-logging
