version: "3.4"

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  admin-frontend:
    restart: "no"
  identifier:
    restart: "no"
    ports:
      - "80:80"
  dispatcher:
    restart: "no"
  database:
    restart: "no"
  delta-notifier:
    restart: "no"
  virtuoso:
    ports:
      - "8890:8890"
    restart: "no"
  file:
    restart: "no"
  kaleidos-public-file:
    restart: "no"
    environment:
      MU_SPARQL_ENDPOINT: "http://kaleidos-db:8895/sparql"
    extra_hosts:
      - "kaleidos-db:172.17.0.1"
  export:
    environment:
      KALEIDOS_SPARQL_ENDPOINT: "http://kaleidos-db:8895/sparql"
    extra_hosts:
      - "kaleidos-db:172.17.0.1"
    restart: "no"
  ttl-to-delta:
    restart: "no"
  publication-producer:
    restart: "no"
