version: '3.4'

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  identifier:
    ports:
      - "80:80"
    restart: "no"
  dispatcher:
    restart: "no"
  virtuoso:
    ports:
      - "8890:8890"
    restart: "no"
  export:
    environment:
      NODE_ENV: "development"
      KALEIDOS_SPARQL_ENDPOINT: "http://kaleidos-db:8895/sparql"
      MU_SPARQL_ENDPOINT: "http://virtuoso:8890/sparql"
    ports:
      - "8888:80"
    links:
      - virtuoso:virtuoso
    extra_hosts:
      - "kaleidos-db:172.17.0.1"
    restart: "no"
